name: Release to NPM Latest
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
      name: Release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            token: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
        - name: 'Setup Tools'
          uses: ./.github/actions/setup-tools
        - name: Build package
          run: pnpm run build
        - name: Release
          run: |
            echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
            npm whoami
            pnpm run shipit
          env:
            GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
